# Dicionário de tradução
traducao = {
   "letra maiúscula a": "A", "letra maiúscula b": "B", "letra maiúscula c": "C",
    "letra maiúscula d": "D", "letra maiúscula e": "E", "letra maiúscula f": "F",
    "letra maiúscula g": "G", "letra maiúscula h": "H", "letra maiúscula i": "I",
    "letra maiúscula j": "J", "letra maiúscula k": "K", "letra maiúscula l": "L",
    "letra maiúscula m": "M", "letra maiúscula n": "N", "letra maiúscula o": "O",
    "letra maiúscula p": "P", "letra maiúscula q": "Q", "letra maiúscula r": "R",
    "letra maiúscula s": "S", "letra maiúscula t": "T", "letra maiúscula u": "U",
    "letra maiúscula v": "V", "letra maiúscula w": "W", "letra maiúscula x": "X",
    "letra maiúscula y": "Y", "letra maiúscula z": "Z",
    "letra minúscula a": "a", "letra minúscula b": "b", "letra minúscula c": "c", 
    "letra minúscula d": "d", "letra minúscula e": "e", "letra minúscula f": "f", 
    "letra minúscula g": "g", "letra minúscula h": "h", "letra minúscula i": "i", 
    "letra minúscula j": "j", "letra minúscula k": "k", "letra minúscula l": "l", 
    "letra minúscula m": "m", "letra minúscula n": "n", "letra minúscula o": "o", 
    "letra minúscula p": "p", "letra minúscula q": "q", "letra minúscula r": "r", 
    "letra minúscula s": "s", "letra minúscula t": "t", "letra minúscula u": "u", 
    "letra minúscula v": "v", "letra minúscula w": "w", "letra minúscula x": "x", 
    "letra minúscula y": "y", "letra minúscula z": "z", 
    "número 0": "0", "número 1": "1", "número 2": "2", 
    "número 3": "3", "número 4": "4", "número 5": "5", 
    "número 6": "6", "número 7": "7", "número 8": "8", 
    "número 9": "9",     
    "número zero": "0", "número um": "1", "número dois": "2",
    "número três": "3", "número quatro": "4", "número cinco": "5",
    "número seis": "6", "número sete": "7", "número oito": "8",
    "número nove": "9",
    "letra maiúscula de": "D", "letra maiúscula efe": "F", "letra maiúscula agá": "H",
    "letra maiúscula jota": "J", "letra maiúscula ka": "K", "letra maiúscula ele": "L",
    "letra maiúscula eme": "M", "letra maiúscula ene": "N", "letra maiúscula erre": "R",
    "letra maiúscula esse": "S", "letra maiúscula te": "T", "letra maiúscula vê": "V",
    "letra maiúscula dáblio": "W", "letra maiúscula xis": "X", "letra maiúscula ípsilon": "Y",
    "letra maiúscula zê": "Z", "letra maiúscula ve": "V", "letra maiúscula que": "Q",
    "letra maiúscula gê": "G", "letra maiúscula pê": "P", "letra maiúscula cé": "C",
    "letra maiúscula bê": "B", "letra maiúscula ê": "E", "letra maiúscula a": "A",
    "letra maiúscula i": "I", "letra maiúscula o": "O", "letra maiúscula u": "U",
    "letra maiúscula ver": "V",
    "letra minúscula de": "d", "letra minúscula efe": "f", "letra minúscula agá": "h",
    "letra minúscula jota": "j", "letra minúscula ka": "k", "letra minúscula ele": "l",
    "letra minúscula eme": "m", "letra minúscula ene": "n", "letra minúscula erre": "r",
    "letra minúscula esse": "s", "letra minúscula te": "t", "letra minúscula vê": "v",
    "letra minúscula dáblio": "w", "letra minúscula xis": "x", "letra minúscula ípsilon": "y",
    "letra minúscula zê": "z", "letra minúscula ve": "v", "letra minúscula que": "q",
    "letra minúscula gê": "g", "letra minúscula pê": "p", "letra minúscula cé": "c",
    "letra minúscula bê": "b", "letra minúscula ê": "e", "letra minúscula a": "a",
    "letra minúscula i": "i", "letra minúscula o": "o", "letra minúscula u": "u",
    "letra minúscula ver": "v"
}