import os
import requests
import json

# URL da API do Bitrix24 via variável de ambiente
url_api_bitrix24 = os.getenv('BITRIX24_API_URL', "https://smartsupply.bitrix24.com.br/rest/16/canbg9vx6rag1mox/")
pasta_respostas = os.getenv('RESPOSTAS_DIR', os.path.join(os.path.dirname(__file__), 'respostas'))

# Criar diretório de respostas se não existir
os.makedirs(pasta_respostas, exist_ok=True)

# Adicione mais codificações se necessário
codificacoes_possiveis = ['utf-8', 'iso-8859-1', 'windows-1252']


pergunta_1 = "QUALIFICAÇÃO TÉCNICA  É A COMPROVAÇÃO DE QUE A EMPRESA TEM EXPERIÊNCIA E COMPETÊNCIA PARA EXECUTAR O SERVIÇO OU FORNECER O PRODUTO SOLICITADO. ELE SERVE COMO UMA GARANTIA DE QUE A EMPRESA JÁ REALIZOU COM SUCESSO TRABALHOS SEMELHANTES AO QUE ESTÁ SENDO LICITADO.COM BASE NESSAS EXPLICAÇÕES,ME INFORME QUAL A QUALIFICAÇÃO TECNICA COMPLETA EXIGIDA, EXIGE ALGUM QUANTITATIVO DE ALGO, SE SIM ME RESPONDA  de forma DETALHADA, EU QUERO UMA RESPOSTA CLARA E COMPLETA. PROCURE ESSA INFORMAÇÃO E EXPLIQUE O CONTEXTO DA RESPOSTA DE FORMA RESUMIDA RESPONDA EM PORTUGUES"
pergunta_2 = "OS CRITERIOS DE JULGAMENTO DE ITENS SÃO DIVIDOS DA SEGUINTE FORMA, MENOR PREÇO POR ITEM, NELE  CADA ITEM DA LICITAÇÃO É AVALIADO SEPARADAMENTE. O VENCEDOR É ESCOLHIDO PARA CADA ITEM INDIVIDUALMENTE, COM BASE NA PROPOSTA MAIS VANTAJOSA PARA CADA ITEM ESPECÍFICO.MENOR PREÇO POR GRUPO, NELE A LICITAÇÃO É DIVIDIDA EM GRUPOS DE ITENS RELACIONADOS. A AVALIAÇÃO E A ESCOLHA DO VENCEDOR SÃO FEITAS CONSIDERANDO O PREÇO E A PROPOSTA DE CADA GRUPO COMO UM TODO, NÃO INDIVIDUALMENTE POR ITEM E MENOR PREÇO GLOBAL, NELE  A AVALIAÇÃO E ESCOLHA DO VENCEDOR CONSIDERAM O CONJUNTO TOTAL DE TODOS OS ITENS DA LICITAÇÃO. A PROPOSTA VENCEDORA É A QUE APRESENTA A MELHOR CONDIÇÃO PARA A TOTALIDADE DOS ITENS, LEVANDO EM CONTA O VALOR GLOBAL. COM BASE NESSAS INFORMAÇÕES, ME RESPONDA NESTE EDITAL QUAL O CRITÉRIO DE JULGAMENTO DO ITEM É MENOR PREÇO POR ITEM, MENOR PREÇO GLOBAL OU MENOR PREÇO DO GRUPO? PROCURE ESSA INFORMAÇÃO E EXPLIQUE O CONTEXTO DA RESPOSTA DE FORMA RESUMIDA RESPONDA EM PORTUGUES"
pergunta_3 = "QUAL O ENDEREÇO SERÁ PRESTADO O SERVIÇO OU ENTREGUE O MATERIAL?RESPONDA EM PORTUGUES"
pergunta_4 = "QUAL O E-MAIL E TELEFONE DO CONTRATANTE ou o contato para que eu solicite esclarecimentos sobre as minhas dúvidas? RESPONDA EM PORTUGUES"
pergunta_5 = "É PERMITIDO A  SUBCONTRATAÇÃO? PROCURE ESSA INFORMAÇÃO E EXPLIQUE O CONTEXTO DA RESPOSTA DE FORMA RESUMIDA RESPONDA EM PORTUGUES"
pergunta_6 = "QUAL O PRAZO DE VIGÊNCIA DO CONTRATO?RESPONDA EM PORTUGUES"
pergunta_7 = "QUAIS AS DECLARAÇÕES EU PRECISO EMITIR? RESPONDA EM PORTUGUES"
pergunta_8 = "QUAL O INTERVALO DE LANCES?RESPONDA EM PORTUGUES"
pergunta_9 = "O MODO DE DISPUTA DEFINE COMO AS EMPRESAS COMPETEM ENTRE SI PARA VENCER UMA LICITAÇÃO. A LEI 14.133, NOVA LEI DE LICITAÇÕES E CONTRATOS ADMINISTRATIVOS, PREVÊ DOIS MODOS PRINCIPAIS: QUE SÃO ABERTO E ABERTO E FECHADO. NESTE EDITAL, QUAL O MODO DE DISPUTA? RESPONDA APENAS UMA DAS (ABERTO, ABERTO E FECHADO, FECHADO, ALEATORIO )RESPONDA EM PORTUGUES"
pergunta_10 = "QUAL O TIPO DE LANCE OFERTADO? RESPONDA APENAS UMA OPÇÃO (UNITARIO OU TOTAL)RESPONDA EM PORTUGUES"
pergunta_11 = "QUALIFICAÇÃO FINANCEIRA É UMA ETAPA DO PROCESSO DE LICITAÇÃO PÚBLICA QUE VERIFICA SE UMA EMPRESA POSSUI A SAÚDE FINANCEIRA NECESSÁRIA PARA EXECUTAR UM CONTRATO. ELA AVALIA A CAPACIDADE DA EMPRESA DE CUMPRIR COM AS OBRIGAÇÕES FINANCEIRAS DURANTE A EXECUÇÃO DO PROJETO. OS DOCUMENTOS NECESSÁRIOS PARA APRESENTAÇÃO DE COMPROVAÇÃO BALANÇO PATRIMONIAL REGISTRADO NA JUNTA COMERCIAL OU SPED,DEMONSTRAÇÃO DE RESULTADO, ÍNDICES ECONÔMICOS COM BASE NESSAS INFORMAÇÕES, ME RESPONDA QUAL A QUALIFICAÇÃO FINANCEIRA NECESSARIA? (BALANÇO, CERTIDÃO DE FALêNCIA, CAPITAL SOCIAL)RESPONDA EM PORTUGUES"
pergunta_12 = "QUAL O PRAZO DE PAGAMENTO DA PRESTAÇÃO DO SERVIÇO?RESPONDA EM PORTUGUES"
pergunta_13 = " OS TIPOS DE CONTRATAÇÕES PODEM SER TRÊS REGISTRO DE PREÇOS, AQUISIÇÃO OU CONTINUO. O REGISTRO DE PREÇOS: É UTILIZADO PARA FUTURAS AQUISIÇÕES. A ADMINISTRAÇÃO PÚBLICA REGISTRA OS PREÇOS DE FORNECEDORES E CONTRATA CONFORME A NECESSIDADE AO LONGO DE UM PERÍODO (GERALMENTE ATÉ 12 MESES), SEM COMPROMISSO IMEDIATO DE COMPRA OU AQUISIÇÃO IMEDIATA: É GERALMENTE UTILIZADA PARA COMPRAS DE PRODUTOS OU EQUIPAMENTOS, A COMPRA É FEITA DE FORMA DIRETA E IMEDIATA. APÓS A CONCLUSÃO DA LICITAÇÃO, A ADMINISTRAÇÃO PÚBLICA ADQUIRE O BEM OU SERVIÇO DE UMA VEZ, CONFORME ESPECIFICADO NO EDITAL. COM BASE NESSAS INFORMAÇÕES E A DE SERVIÇOS CONTINUOS GERALMENTE SÃO PARA CASOS DE SERVIÇOS E POSSUEM UMA  VIGÊNCIA DO CONTRATO DE SERVIÇOS CONTÍNUOS É DEFINIDA NO EDITAL E PODE SER PRORROGADA, ENQUANTO A SOLICITAÇÃO DO SERVIÇO É FEITA ATRAVÉS DE ORDENS DE SERVIÇO OU SEGUNDO UM CRONOGRAMA ESTABELECIDO.NESTE EDITAL QUAL É O  TIPO DE CONTRATAÇÃO DESTE EDITAL? RESPONDA APENAS UMA DAS OPÇÕES(AQUISIÇÃO, REGISTRO DE PREÇO OU SERVIÇO CONTINUO)RESPONDA EM PORTUGUES. EU NÃO QUERO QUE VOCÊ ME RESPONDA SE É OU NÃO UMA CONTRATAÇÃO DE SERVIÇOS CONTINUOS, APENAS ME RESPONDA AS EXIGENCIAS CASO A RESPOSTA SEJA SIM"
pergunta_14 = "QUAIS OS PRINCIPAIS PONTOS PASSIVEIS DE DESCLASSIFICAÇÃO?RESPONDA EM PORTUGUES"
pergunta_15 = "EM ALGUMAS LICITAÇÕES, É EXIGIDA A APRESENTAÇÃO DE CERTIFICAÇÕES ESPECÍFICAS. ESSAS CERTIFICAÇÕES SÃO DOCUMENTOS QUE COMPROVAM QUE A EMPRESA OU OS PRODUTOS/SERVIÇOS QUE ELA OFERECE ATENDEM A DETERMINADOS PADRÕES DE QUALIDADE, SEGURANÇA, OU COMPETÊNCIA TÉCNICA. AQUI ESTÃO ALGUNS EXEMPLOS DE CERTIFICAÇÕES EXTRAS QUE SÃO SOLICITADAS: A ISO 9001 (QUALIDADE), ISO 14001 (MEIO AMBIENTE) ETC.CERTIFICAÇÕES SETORIAIS: ESPECÍFICAS PARA CERTOS SETORES, COMO ANVISA PARA PRODUTOS DE SAÚDE OU INMETRO PARA PRODUTOS INDUSTRIAIS.CERTIFICAÇÕES NO CONSELHO: COMO CREA, CRAU, CRM, ANATEL, ANTT, PMP PARA GERENCIAMENTO DE PROJETOS.NESTE EDITAL, HÁ ALGUMA DESSAS EXIGENCIAS NESTE EDITAL?RESPONDA EM PORTUGUES"
pergunta_16 = "QUAL O PRAZO DE VALIDADE MINIMO PARA O CADASTRO DA PROPOSTA? RESPONDA APENAS EM NÚMEROS INTEIROS A QUANTIDADE DE DIAS E RESPONDA EM PORTUGUES"
pergunta_17 = "A LICITANTE ARREMATANTE, TERÁ QUANTO TEMPO PARA APRESENTAR A PROPOSTA ATUALIZADA OU RESPONDER AS DILIGÊNCIAS?RESPONDA EM PORTUGUES"
pergunta_18 = "A EXIGÊNCIA DE UM ESCRITÓRIO NO LOCAL GERALMENTE OCORRE EM LICITAÇÕES QUE ENVOLVEM SERVIÇOS CONTÍNUOS OU PROJETOS QUE NECESSITAM DE SUPERVISÃO E INTERAÇÃO FREQUENTE. NESTE EDITAL É OBRIGATÓRIO POSSUIR ESCRITÓRIO OU SEDE NO LOCAL QUE SERÁ PRESTADO O SERVIÇO? RESPONDA SIM OU NÃO E  JUSTIFIQUE, RESPONDA EM PORTUGUES"
pergunta_19 = "A LEI 14.133 GARANTE A EXCLUSIVIDADE PARA ME (MICROEMPRESA) E EPP (EMPRESA DE PEQUENO PORTE) EM ALGUMAS LICITAÇÕES PÚBLICAS E ISSO  É UMA POLÍTICA QUE RESERVA DETERMINADAS OPORTUNIDADES DE CONTRATAÇÃO EXCLUSIVAMENTE PARA ESSAS EMPRESAS. ESSA MEDIDA VISA FOMENTAR O DESENVOLVIMENTO ECONÔMICO E SOCIAL, PROMOVIDO A COMPETITIVIDADE E A SUSTENTABILIDADE DOS PEQUENOS NEGÓCIOS. A EXCLUSIVIDADE É PREVISTA NA LEI COMPLEMENTAR Nº 123/2006, CONHECIDA COMO LEI GERAL DA MICRO E PEQUENA EMPRESA. COM BASE NESSAS INFORMAÇÕES, EU QUERO QUE VOCÊ ME INFORME SE NESTE EDITAL SOMENTE MICRO EMPRESAS (ME, EPP)PODEM PARTICIPAR DESSA LICITAÇÃO, É UMA LICITAÇÃO EXCLUSIVA PARA ME,EPP? PROCURE ESSA INFORMAÇÃO E EXPLIQUE O CONTEXTO DA RESPOSTA DE FORMA RESUMIDA RESPONDA EM PORTUGUES"
pergunta_20 = "A VISTORIA OBRIGATÓRIA EM LICITAÇÕES PÚBLICAS É UM REQUISITO QUE DETERMINA QUE AS EMPRESAS INTERESSADAS EM PARTICIPAR DO PROCESSO DE LICITAÇÃO DEVEM REALIZAR UMA VISITA TÉCNICA AO LOCAL ONDE SERÁ EXECUTADO O SERVIÇO OU FORNECIDO O PRODUTO. ESSA VISTORIA TEM COMO OBJETIVO GARANTIR QUE OS LICITANTES CONHEÇAM DETALHADAMENTE AS CONDIÇÕES E PARTICULARIDADES DO LOCAL, PARA QUE POSSAM ELABORAR PROPOSTAS MAIS PRECISAS E REALISTAS.NESTE EDITAL EU SOU OBRIGADO A FAZER A VISITA TÉCNICA? PROCURE ESSA INFORMAÇÃO E EXPLIQUE O CONTEXTO DA RESPOSTA DE FORMA RESUMIDA RESPONDA EM PORTUGUES"
pergunta_21 = "QUAIS SÃO AS EXIGÊNCIAS PARA A PROPOSTA? RESPONDA EM PORTUGUES"
pergunta_22 = "FOI DESTACADO ALGUMA OBSERVAÇÃO SE SIM, CITE QUAL OU NÃO? RESPONDA EM PORTUGUES"
pergunta_23 = "HÁ ALGUMA EXIGÊNCIA ALÉM DAS OBRIGATÓRIAS NO SICAF? PROCURE ESSA INFORMAÇÃO E EXPLIQUE O CONTEXTO DA RESPOSTA DE FORMA RESUMIDA RESPONDA EM PORTUGUES"
pergunta_24 = "QUAL FOI O VALOR TOTAL ESTIMADO PARA A CONTRATAÇÃO? CASO NÃO ENCONTRE, PROCURE SE É SIGILOSO, RESPONDA EM VALOR DE MOEDA BRASILEIRA APENAS EM NÚMEROS (RESPONDA EM PORTUGUES"
pergunta_25 = "O PREGÃO SERÁ REALIZADO EM ALGUM PORTAL OU SERÁ PRESENCIAL? SE FOR PRESENCIAL RESPONDA SIM SE FOR EM ALGUM PORTAL RESPONDA NÃO E EM PORTUGUES"
pergunta_26 = "QUAL O PRAZO PARA ENTREGA DO OBJETO CONTRATADO? RESPONDA EM PORTUGUES"
pergunta_27 = "SE A CONTRATAÇÃO FOR DE SERVIÇOS CONTÍNUOS, QUAL É A QUANTIDADE TOTAL DE TRABALHADORES CONTRATADOS E AS RESPECTIVAS FUNÇÕES DESCRITAS NA PLANILHA DE COMPOSIÇÃO DE CUSTOS? RESPONDA EM PORTUGUÊS"
pergunta_28 = "SE A CONTRATAÇÃO FOR DE SERVIÇOS CONTÍNUOS, HÁ PREVISÃO DE SERVIÇOS ADICIONAIS COMO LIMPEZA DE VIDROS E FACHADAS, ÁREAS EXTERNAS, EVENTOS, TRATAMENTO DE PISOS E CARPETES, DESINFECÇÃO, FORNECIMENTO DE MATERIAIS DE LIMPEZA, JARDINAGEM, LIMPEZA DE CAIXAS D'ÁGUA, COLETA SELETIVA E LIMPEZA EM ALTURA NA PLANILHA DE COMPOSIÇÃO DE CUSTOS? RESPONDA EM PORTUGUÊS"
pergunta_29 = "SE A CONTRATAÇÃO FOR DE SERVIÇOS CONTÍNUOS, QUAL O VALOR TOTAL MENSAL DO VALE ALIMENTAÇÃO PAGO AOS FUNCIONÁRIOS, SEGUNDO A PLANILHA DE COMPOSIÇÃO DE CUSTOS? RESPONDA EM PORTUGUÊS"
pergunta_30 = "SE A CONTRATAÇÃO FOR DE SERVIÇOS CONTÍNUOS, HÁ PREVISÃO DE PAGAMENTO DE SEGURO DE VIDA AOS FUNCIONÁRIOS NA PLANILHA DE COMPOSIÇÃO DE CUSTOS? RESPONDA EM PORTUGUÊS."
pergunta_31 = "SE A CONTRATAÇÃO FOR DE SERVIÇOS CONTÍNUOS, HÁ PREVISÃO DE PAGAMENTO DE ALGUM AUXÍLIO AOS FUNCIONÁRIOS NA PLANILHA DE COMPOSIÇÃO DE CUSTOS? RESPONDA EM PORTUGUÊS."
pergunta_32 = "SE A CONTRATAÇÃO FOR DE SERVIÇOS CONTÍNUOS, QUAL O VALOR TOTAL MENSAL PREVISTO PARA PAGAMENTO DE UNIFORMES DOS FUNCIONÁRIOS, SEGUNDO A PLANILHA DE COMPOSIÇÃO DE CUSTOS? RESPONDA EM PORTUGUÊS."
pergunta_33 = "SE A CONTRATAÇÃO FOR DE SERVIÇOS CONTÍNUOS, QUAL O VALOR TOTAL MENSAL PREVISTO PARA PAGAMENTO DE MATERIAIS PARA A EXECUÇÃO DO SERVIÇO E ESSE VALOR SERÁ REEMBOLSADO NA NOTA, SEGUNDO A PLANILHA DE COMPOSIÇÃO DE CUSTOS? RESPONDA EM PORTUGUÊS."
pergunta_34 = "SE A CONTRATAÇÃO FOR DE SERVIÇOS CONTÍNUOS, QUAL O VALOR TOTAL MENSAL PREVISTO PARA PAGAMENTO DE EQUIPAMENTOS DURANTE A VIGÊNCIA DO CONTRATO, SEGUNDO A PLANILHA DE COMPOSIÇÃO DE CUSTOS? RESPONDA EM PORTUGUÊS."
pergunta_35 = "SE A CONTRATAÇÃO FOR DE SERVIÇOS CONTÍNUOS, HÁ PREVISÃO DE REALIZAÇÃO DE ALGUMA MANUTENÇÃO, COMO LIMPEZA DE FACHADA OU JARDIM, SEGUNDO A PLANILHA DE COMPOSIÇÃO DE CUSTOS? RESPONDA EM PORTUGUÊS."
pergunta_36 = "SE A CONTRATAÇÃO FOR DE SERVIÇOS CONTÍNUOS, SERÁ EXIGIDA A APRESENTAÇÃO DE ALGUM LAUDO NA EXECUÇÃO DO CONTRATO? DETALHE A INFORMAÇÃO SEGUNDO A PLANILHA DE COMPOSIÇÃO DE CUSTOS. RESPONDA EM PORTUGUÊS."
pergunta_37 = "SE A CONTRATAÇÃO FOR DE SERVIÇOS CONTÍNUOS, HAVERÁ REPASSE DE ALGUM REEMBOLSO, SEGUNDO A PLANILHA DE COMPOSIÇÃO DE CUSTOS? RESPONDA EM PORTUGUÊS."
pergunta_38 = "QUAL A ORIENTAÇÃO PARA PARTICIPAÇÃO DE EMPRESAS OPTANTES PELO SIMPLES,PODE-SE UTILIZAR DO BENEFICIO? EM PORTUGUÊS"
pergunta_39 = "SE A CONTRATAÇÃO FOR DE SERVIÇOS CONTÍNUOS, QUAL O SINDICATO OU CONVENÇÃO COLETIVA INDICADO, SEGUNDO A PLANILHA DE COMPOSIÇÃO DE CUSTOS? RESPONDA EM PORTUGUÊS."
pergunta_40 = "SE A CONTRATAÇÃO FOR DE SERVIÇOS CONTÍNUOS, HÁ PREVISÃO DE CONTA VINCULADA OU SEGURO GARANTIA, SEGUNDO A PLANILHA DE COMPOSIÇÃO DE CUSTOS? RESPONDA EM PORTUGUÊS"


def ler_arquivo_json(caminho_arquivo):
    for codificacao in codificacoes_possiveis:
        try:
            with open(caminho_arquivo, 'r', encoding=codificacao) as arquivo:
                return json.load(arquivo)
        except UnicodeDecodeError:
            continue
    raise Exception(f'Não foi possível ler o arquivo {caminho_arquivo} com as codificações testadas.')

def obter_info_cartoes_na_etapa(id_pipeline, id_etapa):
    endpoint = "crm.deal.list"
    parametros = {
        "filter": {"=STAGE_ID": id_etapa, "=CATEGORY_ID": id_pipeline},
        "select": ["ID", "UF_CRM_1697549977"],
    }
    response = requests.post(url_api_bitrix24 + endpoint, json=parametros)
    if response.status_code == 200:
        return response.json()["result"]
    else:
        print(f"Erro ao obter informações dos cartões de negócio. Código de status: {response.status_code}")
        return None
    
# Método para atualizar o cartão de negócio
def atualizar_cartao_negocio(id_cartao, dados_atualizacao):
    endpoint = "crm.deal.update"
    headers = {'Content-Type': 'application/json'}
    data = {"id": id_cartao, "fields": dados_atualizacao}
    response = requests.post(url_api_bitrix24 + endpoint, headers=headers, data=json.dumps(data))
    if response.status_code == 200:
        return response.json()
    else:
        print(f"Erro: {response.status_code}, Resposta: {response.text}")
        return None

def processar_atualizacoes(id_pipeline, id_etapa):
    cartoes_na_etapa = obter_info_cartoes_na_etapa(id_pipeline, id_etapa)
    if not cartoes_na_etapa:
        print("Nenhum cartão encontrado na etapa especificada.")
        return

    for nome_arquivo in os.listdir(pasta_respostas):
        caminho_arquivo = os.path.join(pasta_respostas, nome_arquivo)
        dados = ler_arquivo_json(caminho_arquivo)
        nome_sem_extensao = os.path.splitext(nome_arquivo)[0]
        cartao_correspondente = next((c for c in cartoes_na_etapa if c.get("UF_CRM_1697549977") == nome_sem_extensao), None)

        if cartao_correspondente:
            id_cartao = cartao_correspondente['ID']

        # Mapeando os dados do JSON para os campos do Bitrix24
            dados_atualizacao = {
            "UF_CRM_1657480073676": dados[pergunta_1],
            "UF_CRM_1704052561": dados[pergunta_2],
            "UF_CRM_1680611704914": dados[pergunta_3],
            "UF_CRM_1674587353724": dados[pergunta_4],
            "UF_CRM_1704052658": dados[pergunta_5],
            "UF_CRM_1657394383051": dados[pergunta_6],
            "UF_CRM_1661533353":    dados[pergunta_7],
            "UF_CRM_1704052824": dados[pergunta_8],
            "UF_CRM_1704052968": dados[pergunta_9],
            "UF_CRM_1704053075": dados[pergunta_10],
            "UF_CRM_1657480058163": dados[pergunta_11],
            "UF_CRM_1695820797444": dados[pergunta_12],
            "UF_CRM_1704052938": dados[pergunta_13],
            "UF_CRM_1663033632":    dados[pergunta_14],
            "UF_CRM_1657480087357": dados[pergunta_15],
            "UF_CRM_1703893799":    dados[pergunta_16],
            "UF_CRM_1663205883544": dados[pergunta_17],
            "UF_CRM_1704052771": dados[pergunta_18],
            "UF_CRM_1704052692": dados[pergunta_19],
            "UF_CRM_1704052644": dados[pergunta_20],
            "UF_CRM_1683153207430": dados[pergunta_21],
            "UF_CRM_1657480114363": dados[pergunta_22],
            "UF_CRM_1680044112142": dados[pergunta_23],
            "UF_CRM_1703860124684": dados[pergunta_24],
            "UF_CRM_1703872101562": dados[pergunta_25],
            "UF_CRM_1705174327217": 'Sim',
            "UF_CRM_1663253782486": dados[pergunta_26],
            "UF_CRM_1706878198": dados[pergunta_27],
            "UF_CRM_1706878215": dados[pergunta_28],
            "UF_CRM_1706878245": dados[pergunta_29],
            "UF_CRM_1706878281": dados[pergunta_30],
            "UF_CRM_1706878308": dados[pergunta_31],
            "UF_CRM_1706878380": dados[pergunta_32],
            "UF_CRM_1706878393": dados[pergunta_33],
            "UF_CRM_1706878484": dados[pergunta_34],
            "UF_CRM_1706878495": dados[pergunta_35],
            "UF_CRM_1706878514": dados[pergunta_36],
            "UF_CRM_1706878527": dados[pergunta_37],
            "UF_CRM_1706881804197": dados[pergunta_38],
            "UF_CRM_1706882826": dados[pergunta_39],
            "UF_CRM_1710441910": dados[pergunta_40]
            }
            resultado = atualizar_cartao_negocio(id_cartao, dados_atualizacao)
            if resultado:
                print(f"Cartão {id_cartao} atualizado com sucesso.")
            else:
                print(f"Falha ao atualizar o cartão {id_cartao}.")
        else:
            print(f"Nenhum cartão correspondente para o arquivo {nome_arquivo}.")
    
# Exemplo de uso
id_pipeline = "32"  # Substitua pelo ID do seu pipeline
id_etapa = "C32:NEW"  # Substitua pela ID da sua etapa
processar_atualizacoes(id_pipeline, id_etapa)
